plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dreamingbully.dreamengine'
    compileSdk 36

    defaultConfig {
        applicationId 'com.dreamingbully.dreamengine'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1.0'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++20', '-O3', '-DNDEBUG'
                arguments '-DANDROID_STL=c++_shared'
            }
        }

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        debug {
            externalNativeBuild {
                cmake {
                    cppFlags '-std=c++20', '-O0', '-g'
                }
            }
        }
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.31.6'
        }
    }
}
